
CREATE TABLE CLIENT
(
    ID_CLIENT INT(10) PRIMARY KEY
    NOM VARCHAR
    (255) NOT NULL,
    PRENOM VARCHAR
    (255) NOT NULL,
    DATE_NAISSANCE DATE ,
);


    CREATE TABLE PRODUIT
    (
        ID_PRODUIT INT(10) PRIMARY KEY
    NOM VARCHAR
        (255) NOT NULL,
    DESCRITPION VARCHAR
        (255) NOT NULL,
    QUANTITY INT
        (10) NOT NULL,
);


        CREATE TABLE COMMANDE
(
    ID_COMMANDE INT(10) PRIMARY KEY,
    ID_CLIENT INT(10),
    ID_PRODUIT INT(10),
    FOREIGN KEY ID_CLIENT REFERENCES CLIENT,
    FOREIGN KEY ID_PRODUIT REFERENCES PRODUIT
);