
CREATE TABLE CLIENT
(
    ID_CLIENT NUMBER(10) PRIMARY KEY
    NOM VARCHAR
    (255) NOT NULL,
    PRENOM VARCHAR
    (255) NOT NULL,
    DATE_NAISSANCE DATE ,
);


    CREATE TABLE PRODUIT
    (
        ID_PRODUIT NUMBER(10) PRIMARY KEY
    NOM VARCHAR
        (255) NOT NULL,
    DESCRITPION VARCHAR
        (255) NOT NULL,
    QUANTITY NUMBER
        (10) NOT NULL,
);


        CREATE TABLE COMMANDE
(
    ID_COMMANDE NUMBER(10) PRIMARY KEY,
    ID_CLIENT NUMBER(10),
    ID_PRODUIT NUMBER(10),
    FOREIGN KEY ID_CLIENT REFERENCES CLIENT,
    FOREIGN KEY ID_PRODUIT REFERENCES PRODUIT
);