DROP TABLE PERSONNE
CASCADE CONSTRAINT;
CREATE TABLE PERSONNE
(
    NOM_PER VARCHAR(10) CONSTRAINT NN_PERSONNE_NOM NOT NULL,
    PRENOM_PER VARCHAR(20) CONSTRAINT NN_PERSONNE_PRENOM NOT NULL,
    DATE_INSCRIPTION DATE ,
    AGE NUMBER(3) CONSTRAINT CK_PERSONNE_AGE CHECK(AGE > 0),
    SEXE CHAR(4) CONSTRAINT CK_PERSONNE_SEX CHECK (SEXE  IN ('F','M')),
    CONSTRAINT PK_PERSONNE PRIMARY KEY (NOM_PER,PRENOM_PER)
);