DROP TABLE PERSONNE
CASCADE CONSTRAINT;
CREATE TABLE CLIENT
(
    ID_CLIENT NUMBER(10) PRIMARY KEY
    NOM VARCHAR
    (10) NOT NULL,
    PRENOM VARCHAR
    (20) NOT NULL,
    DATE_NAISSANCE DATE ,
);